import { pool } from "../server/db.js";

/**
 * Script to add 50 diverse properties from Ahmednagar district using direct SQL
 */

async function addAhmednagarPropertiesSQL() {
  try {
    console.log("Starting to add 50 Ahmednagar properties via SQL...");
    
    // Get available agents
    const agentResult = await pool.query('SELECT id FROM agents LIMIT 5');
    const agents = agentResult.rows;
    
    if (agents.length === 0) {
      console.error("No agents found. Please add agents first.");
      return;
    }
    
    console.log(`Found ${agents.length} agents for property assignment`);
    
    const properties = [
      {
        title: "Spacious 3BHK Villa in Shrirampur",
        description: "Beautiful villa with modern amenities, garden space, and excellent connectivity to Pune-Nashik highway. Perfect for families looking for peaceful living.",
        price: 8500000,
        location: "Shrirampur, Ahmednagar",
        address: "Survey No. 45, Shrirampur Road, Near Shrirampur Railway Station",
        beds: 3,
        baths: 3,
        area: 1800,
        property_type: "Villa",
        type: "buy",
        parking: 2,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047890"
      },
      {
        title: "Luxury 4BHK Independent House in Ahmednagar City",
        description: "Premium independent house with contemporary design, spacious rooms, and all modern facilities in prime location.",
        price: 12000000,
        location: "Ahmednagar City",
        address: "Plot No. 78, Savedi Road, Near Government Hospital",
        beds: 4,
        baths: 4,
        area: 2400,
        property_type: "Independent House",
        type: "buy",
        parking: 3,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047891"
      },
      {
        title: "Modern 2BHK Apartment in Nagar-Pune Road",
        description: "Well-designed apartment with excellent ventilation, modern fittings, and easy access to Pune highway.",
        price: 4500000,
        location: "Nagar-Pune Road, Ahmednagar",
        address: "Flat No. 304, Sunrise Heights, Nagar-Pune Road",
        beds: 2,
        baths: 2,
        area: 1200,
        property_type: "Apartment",
        type: "buy",
        parking: 1,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047892"
      },
      {
        title: "Prime Commercial Shop in Ahmednagar Market",
        description: "Well-located shop in busy market area with high footfall, perfect for retail business.",
        price: 6500000,
        location: "Market Yard, Ahmednagar",
        address: "Shop No. 45, Main Market Complex, Market Yard",
        beds: 0,
        baths: 1,
        area: 800,
        property_type: "Shop",
        type: "buy",
        parking: 0,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047893"
      },
      {
        title: "Modern Office Space in IT Park",
        description: "Contemporary office space with modern infrastructure, suitable for IT companies and startups.",
        price: 8500000,
        location: "IT Park, Ahmednagar",
        address: "Unit 205, Tech Tower, IT Park, MIDC Area",
        beds: 0,
        baths: 2,
        area: 1500,
        property_type: "Office",
        type: "buy",
        parking: 4,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047894"
      },
      {
        title: "Fertile Agricultural Land in Rahuri",
        description: "Prime agricultural land with bore well, suitable for various crops including sugarcane and vegetables.",
        price: 2500000,
        location: "Rahuri, Ahmednagar",
        address: "Survey No. 234, Village Rahuri, Tehsil Rahuri",
        beds: 0,
        baths: 0,
        area: 217800,
        property_type: "Agricultural Plot",
        type: "buy",
        parking: 0,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Warehouse for Rent in MIDC",
        description: "Large warehouse facility with loading dock, suitable for manufacturing and distribution businesses.",
        price: 80000,
        location: "MIDC, Ahmednagar",
        address: "Plot No. 34, MIDC Industrial Area, Ahmednagar",
        beds: 0,
        baths: 2,
        area: 5000,
        property_type: "Warehouse",
        type: "rent",
        parking: 10,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Premium Farmhouse in Ahmednagar Outskirts",
        description: "Luxurious farmhouse with swimming pool, landscaped gardens, and recreational facilities.",
        price: 18000000,
        location: "Ahmednagar Outskirts",
        address: "Survey No. 123, Ahmednagar-Aurangabad Highway, 15 km from city",
        beds: 5,
        baths: 6,
        area: 4500,
        property_type: "Farmhouse",
        type: "buy",
        parking: 6,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047897"
      },
      {
        title: "Luxury Penthouse in Premium Complex",
        description: "Exclusive penthouse with panoramic city views, premium finishes, and top-tier amenities.",
        price: 22000000,
        location: "Race Course Road, Ahmednagar",
        address: "Penthouse, Sky Heights, Race Course Road",
        beds: 4,
        baths: 5,
        area: 3200,
        property_type: "Penthouse",
        type: "buy",
        parking: 3,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047898"
      },
      {
        title: "Affordable 2BHK House in Nevasa",
        description: "Budget-friendly house suitable for first-time buyers, with basic amenities and good connectivity.",
        price: 1800000,
        location: "Nevasa, Ahmednagar",
        address: "House No. 234, Main Road, Nevasa",
        beds: 2,
        baths: 1,
        area: 900,
        property_type: "House",
        type: "buy",
        parking: 1,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Furnished 3BHK Apartment for Rent",
        description: "Fully furnished apartment with modern appliances, ideal for executives and families.",
        price: 25000,
        location: "College Road, Ahmednagar",
        address: "Flat No. 201, Harmony Apartments, College Road",
        beds: 3,
        baths: 2,
        area: 1400,
        property_type: "Apartment",
        type: "rent",
        parking: 1,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047899"
      },
      {
        title: "Manufacturing Unit in Ahmednagar MIDC",
        description: "Complete manufacturing setup with machinery, suitable for textile and engineering industries.",
        price: 15000000,
        location: "MIDC, Ahmednagar",
        address: "Plot No. 67, Phase II, MIDC Industrial Area",
        beds: 0,
        baths: 3,
        area: 8000,
        property_type: "Industrial Plot",
        type: "buy",
        parking: 15,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047895"
      },
      {
        title: "Heritage Wada for Restoration",
        description: "Traditional Maharashtrian wada with heritage value, suitable for restoration and conversion.",
        price: 5500000,
        location: "Old City, Ahmednagar",
        address: "Wada No. 23, Shaniwar Peth, Old Ahmednagar",
        beds: 8,
        baths: 4,
        area: 3500,
        property_type: "House",
        type: "buy",
        parking: 0,
        featured: true,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Modern Studio Apartment in IT Hub",
        description: "Compact studio with smart design, perfect for young professionals working in IT sector.",
        price: 2800000,
        location: "IT Hub, Ahmednagar",
        address: "Unit 105, Smart Homes, IT Hub Area",
        beds: 1,
        baths: 1,
        area: 450,
        property_type: "Studio Apartment",
        type: "buy",
        parking: 1,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047901"
      },
      {
        title: "Duplex Villa with Garden in Shrigonda",
        description: "Spacious duplex villa with private garden, modern amenities, and peaceful environment.",
        price: 9500000,
        location: "Shrigonda, Ahmednagar",
        address: "Plot No. 89, Green Valley, Shrigonda",
        beds: 4,
        baths: 3,
        area: 2200,
        property_type: "Villa",
        type: "buy",
        parking: 2,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047902"
      },
      {
        title: "Commercial Complex with Multiple Units",
        description: "Multi-unit commercial complex with shops and offices, excellent investment opportunity.",
        price: 25000000,
        location: "Highway Junction, Ahmednagar",
        address: "Commercial Complex, Pune-Nashik Highway Junction",
        beds: 0,
        baths: 8,
        area: 12000,
        property_type: "Commercial Complex",
        type: "buy",
        parking: 20,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047903"
      },
      {
        title: "Gated Community Villa in Sangamner",
        description: "Premium villa in gated community with clubhouse, security, and modern amenities.",
        price: 11500000,
        location: "Sangamner, Ahmednagar",
        address: "Villa No. 45, Royal Gardens, Sangamner",
        beds: 3,
        baths: 3,
        area: 2000,
        property_type: "Villa",
        type: "buy",
        parking: 2,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047904"
      },
      {
        title: "Budget Flat for Investment in Newasa",
        description: "Affordable apartment perfect for rental investment with good appreciation potential.",
        price: 2200000,
        location: "Newasa, Ahmednagar",
        address: "Flat No. 102, Shubham Heights, Newasa",
        beds: 2,
        baths: 1,
        area: 850,
        property_type: "Apartment",
        type: "buy",
        parking: 1,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047905"
      },
      {
        title: "Luxury Row House in Prime Location",
        description: "Elegant row house with contemporary design, premium fittings, and excellent location.",
        price: 14500000,
        location: "Race Course Area, Ahmednagar",
        address: "Row House No. 12, Elite Enclave, Race Course Road",
        beds: 4,
        baths: 4,
        area: 2800,
        property_type: "Row House",
        type: "buy",
        parking: 2,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047906"
      },
      {
        title: "Small Plot for Construction in Karjat",
        description: "Residential plot ready for construction, with clear title and all approvals in place.",
        price: 1200000,
        location: "Karjat, Ahmednagar",
        address: "Plot No. 456, Karjat Village, Near School",
        beds: 0,
        baths: 0,
        area: 1800,
        property_type: "Residential Plot",
        type: "buy",
        parking: 0,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Commercial Space for Rent in City Center",
        description: "Prime commercial space suitable for retail showroom, clinic, or office use.",
        price: 35000,
        location: "City Center, Ahmednagar",
        address: "Shop No. 12, City Plaza, Main Road",
        beds: 0,
        baths: 1,
        area: 1000,
        property_type: "Shop",
        type: "rent",
        parking: 2,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Orchard Land with Mango Trees",
        description: "Established mango orchard with mature trees, good irrigation system, and regular income potential.",
        price: 4200000,
        location: "Kopargaon, Ahmednagar",
        address: "Survey No. 167, Kopargaon-Shirdi Road, Village Kopargaon",
        beds: 0,
        baths: 0,
        area: 348480,
        property_type: "Agricultural Plot",
        type: "buy",
        parking: 0,
        featured: true,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Food Processing Unit for Sale",
        description: "Established food processing facility with modern equipment and necessary certifications.",
        price: 12500000,
        location: "Shrirampur, Ahmednagar",
        address: "Industrial Plot No. 89, Shrirampur Industrial Area",
        beds: 0,
        baths: 4,
        area: 6500,
        property_type: "Industrial Plot",
        type: "buy",
        parking: 8,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047896"
      },
      {
        title: "Traditional 3BHK House in Pathardi",
        description: "Charming traditional house with courtyard, well-maintained structure, and peaceful neighborhood.",
        price: 3200000,
        location: "Pathardi, Ahmednagar",
        address: "House No. 156, Main Road, Pathardi",
        beds: 3,
        baths: 2,
        area: 1600,
        property_type: "House",
        type: "buy",
        parking: 1,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Compact 1BHK Flat for Rent in Ahmednagar",
        description: "Affordable rental option with basic amenities, suitable for working professionals or small families.",
        price: 12000,
        location: "Ahmednagar City",
        address: "Building No. 23, Station Road, Near Bus Stand",
        beds: 1,
        baths: 1,
        area: 650,
        property_type: "Apartment",
        type: "rent",
        parking: 0,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Residential cum Commercial Property",
        description: "Ground floor shop with residential flat above, perfect for live-and-work setup.",
        price: 7500000,
        location: "Station Road, Ahmednagar",
        address: "Building No. 67, Station Road, Near Railway Station",
        beds: 2,
        baths: 2,
        area: 1600,
        property_type: "Shop",
        type: "buy",
        parking: 1,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047900"
      },
      {
        title: "Poultry Farm with Infrastructure",
        description: "Established poultry farm with modern infrastructure and steady income generation.",
        price: 6800000,
        location: "Rural Ahmednagar",
        address: "Survey No. 345, Village Babhulgaon, Ahmednagar",
        beds: 1,
        baths: 1,
        area: 15000,
        property_type: "Agricultural Plot",
        type: "buy",
        parking: 3,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Hospital Building for Sale",
        description: "Purpose-built hospital facility with medical equipment and necessary approvals.",
        price: 35000000,
        location: "Medical Square, Ahmednagar",
        address: "Building No. 1, Medical Square, Near Civil Hospital",
        beds: 0,
        baths: 15,
        area: 25000,
        property_type: "Commercial Complex",
        type: "buy",
        parking: 30,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047907"
      },
      {
        title: "Educational Institute Campus",
        description: "Complete educational campus with classrooms, library, playground, and hostel facilities.",
        price: 28000000,
        location: "Education Hub, Ahmednagar",
        address: "Campus Plot, Education City, Ahmednagar-Pune Road",
        beds: 50,
        baths: 25,
        area: 45000,
        property_type: "Commercial Complex",
        type: "buy",
        parking: 50,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047908"
      },
      {
        title: "Petrol Pump with Highway Frontage",
        description: "Operational petrol pump on national highway with high traffic and steady income.",
        price: 45000000,
        location: "Highway Frontage, Ahmednagar",
        address: "Mumbai-Nashik Highway, Km 45, Ahmednagar",
        beds: 0,
        baths: 4,
        area: 8000,
        property_type: "Commercial Complex",
        type: "buy",
        parking: 20,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047909"
      },
      {
        title: "Serviced Apartment for Business Travelers",
        description: "Fully serviced apartment with hotel-like amenities, perfect for business travelers.",
        price: 35000,
        location: "Business District, Ahmednagar",
        address: "Unit 301, Business Suites, Corporate Avenue",
        beds: 1,
        baths: 1,
        area: 600,
        property_type: "Serviced Apartment",
        type: "rent",
        parking: 1,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047910"
      },
      {
        title: "Banquet Hall with Catering Facility",
        description: "Complete banquet facility with catering kitchen, perfect for events and celebrations.",
        price: 18000000,
        location: "Wedding Street, Ahmednagar",
        address: "Plot No. 123, Wedding Street, Near City Center",
        beds: 0,
        baths: 8,
        area: 15000,
        property_type: "Commercial Complex",
        type: "buy",
        parking: 40,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047911"
      },
      {
        title: "Residential Plot in Upcoming Area",
        description: "Well-located residential plot in developing area with good infrastructure prospects.",
        price: 1800000,
        location: "New Development Area, Ahmednagar",
        address: "Plot No. 567, Phase II, New Town Development",
        beds: 0,
        baths: 0,
        area: 2400,
        property_type: "Residential Plot",
        type: "buy",
        parking: 0,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047912"
      },
      {
        title: "Resort Property with Accommodation",
        description: "Established resort with multiple cottages, restaurant, and recreational facilities.",
        price: 32000000,
        location: "Hill Station Road, Ahmednagar",
        address: "Survey No. 456, Hill Station Road, 25 km from city",
        beds: 20,
        baths: 25,
        area: 35000,
        property_type: "Resort",
        type: "buy",
        parking: 30,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047913"
      },
      {
        title: "Co-working Space in Business Hub",
        description: "Modern co-working facility with flexible spaces, meeting rooms, and business services.",
        price: 8500000,
        location: "Business Hub, Ahmednagar",
        address: "Floor 3, Business Center, Corporate Road",
        beds: 0,
        baths: 4,
        area: 3500,
        property_type: "Office",
        type: "buy",
        parking: 15,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047914"
      },
      {
        title: "Dairy Farm with Processing Unit",
        description: "Complete dairy operation with cattle, processing equipment, and distribution network.",
        price: 12000000,
        location: "Dairy Belt, Ahmednagar",
        address: "Survey No. 789, Village Shirur, Dairy Belt Area",
        beds: 2,
        baths: 2,
        area: 25000,
        property_type: "Agricultural Plot",
        type: "buy",
        parking: 5,
        featured: false,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Shopping Mall Space for Lease",
        description: "Prime retail space in popular shopping mall with high footfall and anchor tenants.",
        price: 150000,
        location: "City Mall, Ahmednagar",
        address: "Shop No. 45-46, City Mall, Central Avenue",
        beds: 0,
        baths: 1,
        area: 1200,
        property_type: "Shop",
        type: "rent",
        parking: 0,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047915"
      },
      {
        title: "Vintage Bungalow for Restoration",
        description: "Colonial-era bungalow with heritage value, perfect for restoration and boutique hotel conversion.",
        price: 8500000,
        location: "Heritage Area, Ahmednagar",
        address: "Bungalow No. 7, Heritage Lane, Cantonment Area",
        beds: 6,
        baths: 4,
        area: 4200,
        property_type: "Bungalow",
        type: "buy",
        parking: 3,
        featured: true,
        maharera_registered: false,
        maharera_number: null
      },
      {
        title: "Tech Park Office with Modern Infrastructure",
        description: "State-of-the-art office space in tech park with fiber connectivity and modern amenities.",
        price: 12500000,
        location: "Tech Park, Ahmednagar",
        address: "Building C, Tech Park Phase I, MIDC Area",
        beds: 0,
        baths: 3,
        area: 4000,
        property_type: "Office",
        type: "buy",
        parking: 12,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047916"
      },
      {
        title: "Apartment Complex for Bulk Sale",
        description: "Complete apartment complex with 24 units, perfect for investors or developers.",
        price: 75000000,
        location: "New Township, Ahmednagar",
        address: "Harmony Complex, New Township Development",
        beds: 48,
        baths: 48,
        area: 32000,
        property_type: "Apartment Complex",
        type: "buy",
        parking: 30,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047917"
      },
      {
        title: "Industrial Shed for Manufacturing",
        description: "Ready-to-use industrial shed with heavy power connection and loading facilities.",
        price: 8900000,
        location: "MIDC Phase III, Ahmednagar",
        address: "Shed No. 34, MIDC Phase III, Industrial Area",
        beds: 0,
        baths: 2,
        area: 6000,
        property_type: "Industrial Plot",
        type: "buy",
        parking: 8,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047918"
      },
      {
        title: "Farm House with Swimming Pool",
        description: "Weekend getaway farmhouse with swimming pool, garden, and recreational facilities.",
        price: 16500000,
        location: "Shirdi Road, Ahmednagar",
        address: "Survey No. 678, Shirdi Road, 20 km from city",
        beds: 4,
        baths: 5,
        area: 3800,
        property_type: "Farmhouse",
        type: "buy",
        parking: 5,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047919"
      },
      {
        title: "Multi-storey Commercial Building",
        description: "Four-storey commercial building with shops on ground floor and offices above.",
        price: 42000000,
        location: "Commercial Street, Ahmednagar",
        address: "Building No. 89, Commercial Street, Central Business District",
        beds: 0,
        baths: 12,
        area: 18000,
        property_type: "Commercial Complex",
        type: "buy",
        parking: 25,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047920"
      },
      {
        title: "Premium 2BHK Flat with Amenities",
        description: "Modern apartment with clubhouse, gym, swimming pool, and landscaped gardens.",
        price: 5800000,
        location: "Premium Colony, Ahmednagar",
        address: "Flat No. 501, Royal Residency, Premium Colony",
        beds: 2,
        baths: 2,
        area: 1300,
        property_type: "Apartment",
        type: "buy",
        parking: 1,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047921"
      },
      {
        title: "Guest House with Restaurant",
        description: "Running guest house business with restaurant, ideal for hospitality investment.",
        price: 22000000,
        location: "Tourist Area, Ahmednagar",
        address: "Plot No. 234, Tourist Complex, Near Famous Temple",
        beds: 15,
        baths: 18,
        area: 12000,
        property_type: "Commercial Complex",
        type: "buy",
        parking: 20,
        featured: false,
        maharera_registered: true,
        maharera_number: "P52100047922"
      },
      {
        title: "Residential Bungalow with Large Garden",
        description: "Spacious bungalow with large garden space, fruit trees, and peaceful environment.",
        price: 13500000,
        location: "Garden Area, Ahmednagar",
        address: "Bungalow No. 45, Garden Colony, Green Belt Area",
        beds: 4,
        baths: 4,
        area: 3200,
        property_type: "Bungalow",
        type: "buy",
        parking: 3,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047923"
      },
      {
        title: "Showroom Space in Prime Market",
        description: "Large showroom space in prime market location with high visibility and footfall.",
        price: 18500000,
        location: "Prime Market, Ahmednagar",
        address: "Showroom No. 12-13, Prime Market Complex, Main Road",
        beds: 0,
        baths: 2,
        area: 2500,
        property_type: "Shop",
        type: "buy",
        parking: 3,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047924"
      },
      {
        title: "Luxury Penthouse with Terrace Garden",
        description: "Exclusive penthouse with private terrace garden, jacuzzi, and premium amenities.",
        price: 28000000,
        location: "Sky Line Complex, Ahmednagar",
        address: "Penthouse, Sky Line Towers, Elite Area",
        beds: 4,
        baths: 5,
        area: 3500,
        property_type: "Penthouse",
        type: "buy",
        parking: 3,
        featured: true,
        maharera_registered: true,
        maharera_number: "P52100047925"
      }
    ];
    
    let successCount = 0;
    
    for (const property of properties) {
      try {
        // Get random agent
        const randomAgent = agents[Math.floor(Math.random() * agents.length)];
        
        const insertQuery = `
          INSERT INTO properties (
            title, description, price, location, address, beds, baths, area, area_unit,
            property_type, type, status, featured, features, images, 
            maharera_registered, maharera_number, agent_id, parking, map_url
          ) VALUES (
            $1, $2, $3, $4, $5, $6, $7, $8, 'sqft',
            $9, $10, 'active', $11, '["Modern Amenities", "Good Location"]', '["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop"]',
            $12, $13, $14, $15, $16
          )
        `;
        
        const values = [
          property.title,
          property.description, 
          property.price,
          property.location,
          property.address,
          property.beds,
          property.baths,
          property.area,
          property.property_type,
          property.type,
          property.featured,
          property.maharera_registered,
          property.maharera_number,
          randomAgent.id,
          property.parking,
          `https://maps.google.com/maps?q=${encodeURIComponent(property.location)}`
        ];
        
        await pool.query(insertQuery, values);
        successCount++;
        console.log(`✓ Added property ${successCount}: ${property.title}`);
        
      } catch (error) {
        console.error(`✗ Failed to add property: ${property.title}`);
        console.error("Error:", error.message);
      }
    }
    
    console.log(`\n🎉 Successfully added ${successCount} properties from Ahmednagar district!`);
    console.log("\nProperty types added include:");
    console.log("- Residential: Villas, Houses, Apartments, Studios");
    console.log("- Commercial: Shops, Offices, Warehouses, Complexes");
    console.log("- Agricultural: Farms, Orchards, Dairy Operations");
    console.log("- Industrial: Manufacturing Units, Processing Plants");
    console.log("- Luxury: Farmhouses, Penthouses, Resorts");
    console.log("- Specialized: Hospitals, Schools, Petrol Pumps");
    
  } catch (error) {
    console.error("Error adding Ahmednagar properties:", error);
  }
}

// Run the script
addAhmednagarPropertiesSQL().catch(console.error);