import { db } from "../server/db.js";
import { properties, agents } from "../shared/schema.js";

/**
 * Script to add 50 diverse properties from Ahmednagar district
 */

const ahmednagarProperties = [
  // Residential Properties
  {
    title: "Spacious 3BHK Villa in Shrirampur",
    description: "Beautiful villa with modern amenities, garden space, and excellent connectivity to Pune-Nashik highway. Perfect for families looking for peaceful living.",
    price: 8500000,
    location: "Shrirampur, Ahmednagar",
    address: "Survey No. 45, Shrirampur Road, Near Shrirampur Railway Station",
    beds: 3,
    baths: 3,
    area: 1800,
    areaUnit: "sqft",
    yearBuilt: 2020,
    parking: 2,
    propertyType: "Villa",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Garden", "Car Parking", "Modern Kitchen", "Security", "Water Supply"],
    maharera_registered: true,
    maharera_number: "P52100047890",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop"]
  },
  {
    title: "Luxury 4BHK Independent House in Ahmednagar City",
    description: "Premium independent house with contemporary design, spacious rooms, and all modern facilities in prime location.",
    price: 12000000,
    location: "Ahmednagar City",
    address: "Plot No. 78, Savedi Road, Near Government Hospital",
    beds: 4,
    baths: 4,
    area: 2400,
    areaUnit: "sqft",
    yearBuilt: 2021,
    parking: 3,
    propertyType: "Independent House",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Swimming Pool", "Home Theater", "Gym", "Garden", "Security System"],
    maharera_registered: true,
    maharera_number: "P52100047891",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop"]
  },
  {
    title: "Modern 2BHK Apartment in Nagar-Pune Road",
    description: "Well-designed apartment with excellent ventilation, modern fittings, and easy access to Pune highway.",
    price: 4500000,
    location: "Nagar-Pune Road, Ahmednagar",
    address: "Flat No. 304, Sunrise Heights, Nagar-Pune Road",
    beds: 2,
    baths: 2,
    area: 1200,
    areaUnit: "sqft",
    yearBuilt: 2019,
    parking: 1,
    propertyType: "Apartment",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Lift", "Power Backup", "Water Supply", "Security"],
    maharera_registered: true,
    maharera_number: "P52100047892",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop"]
  },
  {
    title: "Traditional 3BHK House in Pathardi",
    description: "Charming traditional house with courtyard, well-maintained structure, and peaceful neighborhood.",
    price: 3200000,
    location: "Pathardi, Ahmednagar",
    address: "House No. 156, Main Road, Pathardi",
    beds: 3,
    baths: 2,
    area: 1600,
    areaUnit: "sqft",
    yearBuilt: 2015,
    parking: 1,
    propertyType: "House",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Courtyard", "Traditional Design", "Well Water", "Garden"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1549517045-bc93de075e53?w=800&h=600&fit=crop"]
  },
  {
    title: "Compact 1BHK Flat for Rent in Ahmednagar",
    description: "Affordable rental option with basic amenities, suitable for working professionals or small families.",
    price: 12000,
    location: "Ahmednagar City",
    address: "Building No. 23, Station Road, Near Bus Stand",
    beds: 1,
    baths: 1,
    area: 650,
    areaUnit: "sqft",
    yearBuilt: 2018,
    parking: 0,
    propertyType: "Apartment",
    type: "rent",
    status: "active",
    featured: false,
    features: ["Furnished", "Water Supply", "Electricity Backup"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop"]
  },

  // Commercial Properties
  {
    title: "Prime Commercial Shop in Ahmednagar Market",
    description: "Well-located shop in busy market area with high footfall, perfect for retail business.",
    price: 6500000,
    location: "Market Yard, Ahmednagar",
    address: "Shop No. 45, Main Market Complex, Market Yard",
    beds: 0,
    baths: 1,
    area: 800,
    areaUnit: "sqft",
    yearBuilt: 2017,
    parking: 0,
    propertyType: "Shop",
    type: "buy",
    status: "active",
    featured: true,
    features: ["High Footfall", "Main Road", "Commercial Area"],
    maharera_registered: true,
    maharera_number: "P52100047893",
    images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop"]
  },
  {
    title: "Modern Office Space in IT Park",
    description: "Contemporary office space with modern infrastructure, suitable for IT companies and startups.",
    price: 8500000,
    location: "IT Park, Ahmednagar",
    address: "Unit 205, Tech Tower, IT Park, MIDC Area",
    beds: 0,
    baths: 2,
    area: 1500,
    areaUnit: "sqft",
    yearBuilt: 2020,
    parking: 4,
    propertyType: "Office",
    type: "buy",
    status: "active",
    featured: true,
    features: ["IT Infrastructure", "Conference Room", "Cafeteria", "Parking"],
    maharera_registered: true,
    maharera_number: "P52100047894",
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop"]
  },
  {
    title: "Warehouse for Rent in MIDC",
    description: "Large warehouse facility with loading dock, suitable for manufacturing and distribution businesses.",
    price: 80000,
    location: "MIDC, Ahmednagar",
    address: "Plot No. 34, MIDC Industrial Area, Ahmednagar",
    beds: 0,
    baths: 2,
    area: 5000,
    areaUnit: "sqft",
    yearBuilt: 2016,
    parking: 10,
    propertyType: "Warehouse",
    type: "rent",
    status: "active",
    featured: false,
    features: ["Loading Dock", "High Ceiling", "Industrial Power", "Security"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop"]
  },

  // Agricultural Properties
  {
    title: "Fertile Agricultural Land in Rahuri",
    description: "Prime agricultural land with bore well, suitable for various crops including sugarcane and vegetables.",
    price: 2500000,
    location: "Rahuri, Ahmednagar",
    address: "Survey No. 234, Village Rahuri, Tehsil Rahuri",
    beds: 0,
    baths: 0,
    area: 5,
    areaUnit: "acres",
    yearBuilt: null,
    parking: 0,
    propertyType: "Agricultural Plot",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Bore Well", "Fertile Soil", "Road Access", "Irrigation"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop"]
  },
  {
    title: "Orchard Land with Mango Trees",
    description: "Established mango orchard with mature trees, good irrigation system, and regular income potential.",
    price: 4200000,
    location: "Kopargaon, Ahmednagar",
    address: "Survey No. 167, Kopargaon-Shirdi Road, Village Kopargaon",
    beds: 0,
    baths: 0,
    area: 8,
    areaUnit: "acres",
    yearBuilt: null,
    parking: 0,
    propertyType: "Agricultural Plot",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Mango Orchard", "Drip Irrigation", "Storage Room", "Income Generating"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&h=600&fit=crop"]
  },

  // Industrial Properties
  {
    title: "Manufacturing Unit in Ahmednagar MIDC",
    description: "Complete manufacturing setup with machinery, suitable for textile and engineering industries.",
    price: 15000000,
    location: "MIDC, Ahmednagar",
    address: "Plot No. 67, Phase II, MIDC Industrial Area",
    beds: 0,
    baths: 3,
    area: 8000,
    areaUnit: "sqft",
    yearBuilt: 2018,
    parking: 15,
    propertyType: "Industrial Plot",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Manufacturing Setup", "Heavy Power", "Loading Area", "Office Space"],
    maharera_registered: true,
    maharera_number: "P52100047895",
    images: ["https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=800&h=600&fit=crop"]
  },
  {
    title: "Food Processing Unit for Sale",
    description: "Established food processing facility with modern equipment and necessary certifications.",
    price: 12500000,
    location: "Shrirampur, Ahmednagar",
    address: "Industrial Plot No. 89, Shrirampur Industrial Area",
    beds: 0,
    baths: 4,
    area: 6500,
    areaUnit: "sqft",
    yearBuilt: 2019,
    parking: 8,
    propertyType: "Industrial Plot",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Food Grade Equipment", "Cold Storage", "Quality Lab", "Packaging Area"],
    maharera_registered: true,
    maharera_number: "P52100047896",
    images: ["https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=600&fit=crop"]
  },

  // Luxury Properties
  {
    title: "Premium Farmhouse in Ahmednagar Outskirts",
    description: "Luxurious farmhouse with swimming pool, landscaped gardens, and recreational facilities.",
    price: 18000000,
    location: "Ahmednagar Outskirts",
    address: "Survey No. 123, Ahmednagar-Aurangabad Highway, 15 km from city",
    beds: 5,
    baths: 6,
    area: 4500,
    areaUnit: "sqft",
    yearBuilt: 2021,
    parking: 6,
    propertyType: "Farmhouse",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Swimming Pool", "Landscaped Garden", "Guest Rooms", "Recreation Area", "Generator"],
    maharera_registered: true,
    maharera_number: "P52100047897",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop"]
  },
  {
    title: "Luxury Penthouse in Premium Complex",
    description: "Exclusive penthouse with panoramic city views, premium finishes, and top-tier amenities.",
    price: 22000000,
    location: "Race Course Road, Ahmednagar",
    address: "Penthouse, Sky Heights, Race Course Road",
    beds: 4,
    baths: 5,
    area: 3200,
    areaUnit: "sqft",
    yearBuilt: 2022,
    parking: 3,
    propertyType: "Penthouse",
    type: "buy",
    status: "active",
    featured: true,
    features: ["City View", "Private Terrace", "Jacuzzi", "Home Automation", "Concierge Service"],
    maharera_registered: true,
    maharera_number: "P52100047898",
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop"]
  },

  // Budget Properties
  {
    title: "Affordable 2BHK House in Nevasa",
    description: "Budget-friendly house suitable for first-time buyers, with basic amenities and good connectivity.",
    price: 1800000,
    location: "Nevasa, Ahmednagar",
    address: "House No. 234, Main Road, Nevasa",
    beds: 2,
    baths: 1,
    area: 900,
    areaUnit: "sqft",
    yearBuilt: 2016,
    parking: 1,
    propertyType: "House",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Basic Amenities", "Road Access", "Peaceful Area"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop"]
  },
  {
    title: "Small Plot for Construction in Karjat",
    description: "Residential plot ready for construction, with clear title and all approvals in place.",
    price: 1200000,
    location: "Karjat, Ahmednagar",
    address: "Plot No. 456, Karjat Village, Near School",
    beds: 0,
    baths: 0,
    area: 1800,
    areaUnit: "sqft",
    yearBuilt: null,
    parking: 0,
    propertyType: "Residential Plot",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Clear Title", "Construction Ready", "Village Access", "Electricity Available"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&h=600&fit=crop"]
  },

  // Rental Properties
  {
    title: "Furnished 3BHK Apartment for Rent",
    description: "Fully furnished apartment with modern appliances, ideal for executives and families.",
    price: 25000,
    location: "College Road, Ahmednagar",
    address: "Flat No. 201, Harmony Apartments, College Road",
    beds: 3,
    baths: 2,
    area: 1400,
    areaUnit: "sqft",
    yearBuilt: 2020,
    parking: 1,
    propertyType: "Apartment",
    type: "rent",
    status: "active",
    featured: false,
    features: ["Fully Furnished", "Air Conditioning", "Modular Kitchen", "Gym Access"],
    maharera_registered: true,
    maharera_number: "P52100047899",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop"]
  },
  {
    title: "Commercial Space for Rent in City Center",
    description: "Prime commercial space suitable for retail showroom, clinic, or office use.",
    price: 35000,
    location: "City Center, Ahmednagar",
    address: "Shop No. 12, City Plaza, Main Road",
    beds: 0,
    baths: 1,
    area: 1000,
    areaUnit: "sqft",
    yearBuilt: 2019,
    parking: 2,
    propertyType: "Shop",
    type: "rent",
    status: "active",
    featured: false,
    features: ["Prime Location", "High Visibility", "AC", "Parking Available"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=600&fit=crop"]
  },

  // Mixed-Use Properties
  {
    title: "Residential cum Commercial Property",
    description: "Ground floor shop with residential flat above, perfect for live-and-work setup.",
    price: 7500000,
    location: "Station Road, Ahmednagar",
    address: "Building No. 67, Station Road, Near Railway Station",
    beds: 2,
    baths: 2,
    area: 1600,
    areaUnit: "sqft",
    yearBuilt: 2018,
    parking: 1,
    propertyType: "Shop",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Dual Use", "High Footfall", "Residential Flat", "Commercial Ground Floor"],
    maharera_registered: true,
    maharera_number: "P52100047900",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop"]
  },

  // Unique Properties
  {
    title: "Heritage Wada for Restoration",
    description: "Traditional Maharashtrian wada with heritage value, suitable for restoration and conversion.",
    price: 5500000,
    location: "Old City, Ahmednagar",
    address: "Wada No. 23, Shaniwar Peth, Old Ahmednagar",
    beds: 8,
    baths: 4,
    area: 3500,
    areaUnit: "sqft",
    yearBuilt: 1920,
    parking: 0,
    propertyType: "House",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Heritage Property", "Traditional Architecture", "Large Courtyard", "Restoration Potential"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1605276373954-0c4a0dac5b12?w=800&h=600&fit=crop"]
  },

  // Additional Properties (20 more to reach 50)
  {
    title: "Modern Studio Apartment in IT Hub",
    description: "Compact studio with smart design, perfect for young professionals working in IT sector.",
    price: 2800000,
    location: "IT Hub, Ahmednagar",
    address: "Unit 105, Smart Homes, IT Hub Area",
    beds: 1,
    baths: 1,
    area: 450,
    areaUnit: "sqft",
    yearBuilt: 2021,
    parking: 1,
    propertyType: "Studio Apartment",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Smart Home", "Compact Design", "High-Speed Internet", "Security"],
    maharera_registered: true,
    maharera_number: "P52100047901",
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop"]
  },
  {
    title: "Duplex Villa with Garden in Shrigonda",
    description: "Spacious duplex villa with private garden, modern amenities, and peaceful environment.",
    price: 9500000,
    location: "Shrigonda, Ahmednagar",
    address: "Plot No. 89, Green Valley, Shrigonda",
    beds: 4,
    baths: 3,
    area: 2200,
    areaUnit: "sqft",
    yearBuilt: 2020,
    parking: 2,
    propertyType: "Villa",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Duplex Design", "Private Garden", "Solar Panels", "Rain Water Harvesting"],
    maharera_registered: true,
    maharera_number: "P52100047902",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop"]
  },
  {
    title: "Commercial Complex with Multiple Units",
    description: "Multi-unit commercial complex with shops and offices, excellent investment opportunity.",
    price: 25000000,
    location: "Highway Junction, Ahmednagar",
    address: "Commercial Complex, Pune-Nashik Highway Junction",
    beds: 0,
    baths: 8,
    area: 12000,
    areaUnit: "sqft",
    yearBuilt: 2019,
    parking: 20,
    propertyType: "Commercial Complex",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Multiple Units", "Highway Location", "High ROI", "Established Tenants"],
    maharera_registered: true,
    maharera_number: "P52100047903",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop"]
  },
  {
    title: "Poultry Farm with Infrastructure",
    description: "Established poultry farm with modern infrastructure and steady income generation.",
    price: 6800000,
    location: "Rural Ahmednagar",
    address: "Survey No. 345, Village Babhulgaon, Ahmednagar",
    beds: 1,
    baths: 1,
    area: 15000,
    areaUnit: "sqft",
    yearBuilt: 2017,
    parking: 3,
    propertyType: "Agricultural Plot",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Poultry Setup", "Income Generating", "Modern Infrastructure", "Feed Storage"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&h=600&fit=crop"]
  },
  {
    title: "Gated Community Villa in Sangamner",
    description: "Premium villa in gated community with clubhouse, security, and modern amenities.",
    price: 11500000,
    location: "Sangamner, Ahmednagar",
    address: "Villa No. 45, Royal Gardens, Sangamner",
    beds: 3,
    baths: 3,
    area: 2000,
    areaUnit: "sqft",
    yearBuilt: 2021,
    parking: 2,
    propertyType: "Villa",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Gated Community", "Clubhouse", "Swimming Pool", "24/7 Security"],
    maharera_registered: true,
    maharera_number: "P52100047904",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop"]
  },
  {
    title: "Budget Flat for Investment in Newasa",
    description: "Affordable apartment perfect for rental investment with good appreciation potential.",
    price: 2200000,
    location: "Newasa, Ahmednagar",
    address: "Flat No. 102, Shubham Heights, Newasa",
    beds: 2,
    baths: 1,
    area: 850,
    areaUnit: "sqft",
    yearBuilt: 2018,
    parking: 1,
    propertyType: "Apartment",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Investment Property", "Good Rental Yield", "Growing Area"],
    maharera_registered: true,
    maharera_number: "P52100047905",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop"]
  },
  {
    title: "Luxury Row House in Prime Location",
    description: "Elegant row house with contemporary design, premium fittings, and excellent location.",
    price: 14500000,
    location: "Race Course Area, Ahmednagar",
    address: "Row House No. 12, Elite Enclave, Race Course Road",
    beds: 4,
    baths: 4,
    area: 2800,
    areaUnit: "sqft",
    yearBuilt: 2022,
    parking: 2,
    propertyType: "Row House",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Premium Location", "Contemporary Design", "Private Garden", "High-End Finishes"],
    maharera_registered: true,
    maharera_number: "P52100047906",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop"]
  },
  {
    title: "Hospital Building for Sale",
    description: "Purpose-built hospital facility with medical equipment and necessary approvals.",
    price: 35000000,
    location: "Medical Square, Ahmednagar",
    address: "Building No. 1, Medical Square, Near Civil Hospital",
    beds: 0,
    baths: 15,
    area: 25000,
    areaUnit: "sqft",
    yearBuilt: 2016,
    parking: 30,
    propertyType: "Commercial Complex",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Medical Infrastructure", "Backup Power", "Medical Gas Pipeline", "Large Parking"],
    maharera_registered: true,
    maharera_number: "P52100047907",
    images: ["https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=600&fit=crop"]
  },
  {
    title: "Educational Institute Campus",
    description: "Complete educational campus with classrooms, library, playground, and hostel facilities.",
    price: 28000000,
    location: "Education Hub, Ahmednagar",
    address: "Campus Plot, Education City, Ahmednagar-Pune Road",
    beds: 50,
    baths: 25,
    area: 45000,
    areaUnit: "sqft",
    yearBuilt: 2015,
    parking: 50,
    propertyType: "Commercial Complex",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Educational Infrastructure", "Hostels", "Sports Facilities", "Large Campus"],
    maharera_registered: true,
    maharera_number: "P52100047908",
    images: ["https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop"]
  },
  {
    title: "Petrol Pump with Highway Frontage",
    description: "Operational petrol pump on national highway with high traffic and steady income.",
    price: 45000000,
    location: "Highway Frontage, Ahmednagar",
    address: "Mumbai-Nashik Highway, Km 45, Ahmednagar",
    beds: 0,
    baths: 4,
    area: 8000,
    areaUnit: "sqft",
    yearBuilt: 2018,
    parking: 20,
    propertyType: "Commercial Complex",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Highway Location", "High Traffic", "Established Business", "Multiple Revenue Streams"],
    maharera_registered: true,
    maharera_number: "P52100047909",
    images: ["https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&h=600&fit=crop"]
  },
  {
    title: "Serviced Apartment for Business Travelers",
    description: "Fully serviced apartment with hotel-like amenities, perfect for business travelers.",
    price: 35000,
    location: "Business District, Ahmednagar",
    address: "Unit 301, Business Suites, Corporate Avenue",
    beds: 1,
    baths: 1,
    area: 600,
    areaUnit: "sqft",
    yearBuilt: 2020,
    parking: 1,
    propertyType: "Serviced Apartment",
    type: "rent",
    status: "active",
    featured: false,
    features: ["Housekeeping", "WiFi", "Business Center", "Concierge"],
    maharera_registered: true,
    maharera_number: "P52100047910",
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&h=600&fit=crop"]
  },
  {
    title: "Banquet Hall with Catering Facility",
    description: "Complete banquet facility with catering kitchen, perfect for events and celebrations.",
    price: 18000000,
    location: "Wedding Street, Ahmednagar",
    address: "Plot No. 123, Wedding Street, Near City Center",
    beds: 0,
    baths: 8,
    area: 15000,
    areaUnit: "sqft",
    yearBuilt: 2019,
    parking: 40,
    propertyType: "Commercial Complex",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Banquet Halls", "Commercial Kitchen", "Parking Space", "Event Infrastructure"],
    maharera_registered: true,
    maharera_number: "P52100047911",
    images: ["https://images.unsplash.com/photo-1519167758481-83f29c7c8e86?w=800&h=600&fit=crop"]
  },
  {
    title: "Residential Plot in Upcoming Area",
    description: "Well-located residential plot in developing area with good infrastructure prospects.",
    price: 1800000,
    location: "New Development Area, Ahmednagar",
    address: "Plot No. 567, Phase II, New Town Development",
    beds: 0,
    baths: 0,
    area: 2400,
    areaUnit: "sqft",
    yearBuilt: null,
    parking: 0,
    propertyType: "Residential Plot",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Developing Area", "Good Connectivity", "Infrastructure Ready", "Investment Potential"],
    maharera_registered: true,
    maharera_number: "P52100047912",
    images: ["https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&h=600&fit=crop"]
  },
  {
    title: "Resort Property with Accommodation",
    description: "Established resort with multiple cottages, restaurant, and recreational facilities.",
    price: 32000000,
    location: "Hill Station Road, Ahmednagar",
    address: "Survey No. 456, Hill Station Road, 25 km from city",
    beds: 20,
    baths: 25,
    area: 35000,
    areaUnit: "sqft",
    yearBuilt: 2017,
    parking: 30,
    propertyType: "Resort",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Resort Business", "Multiple Cottages", "Restaurant", "Swimming Pool", "Nature Location"],
    maharera_registered: true,
    maharera_number: "P52100047913",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop"]
  },
  {
    title: "Co-working Space in Business Hub",
    description: "Modern co-working facility with flexible spaces, meeting rooms, and business services.",
    price: 8500000,
    location: "Business Hub, Ahmednagar",
    address: "Floor 3, Business Center, Corporate Road",
    beds: 0,
    baths: 4,
    area: 3500,
    areaUnit: "sqft",
    yearBuilt: 2021,
    parking: 15,
    propertyType: "Office",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Flexible Spaces", "Meeting Rooms", "High-Speed Internet", "Business Services"],
    maharera_registered: true,
    maharera_number: "P52100047914",
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop"]
  },
  {
    title: "Dairy Farm with Processing Unit",
    description: "Complete dairy operation with cattle, processing equipment, and distribution network.",
    price: 12000000,
    location: "Dairy Belt, Ahmednagar",
    address: "Survey No. 789, Village Shirur, Dairy Belt Area",
    beds: 2,
    baths: 2,
    area: 25000,
    areaUnit: "sqft",
    yearBuilt: 2018,
    parking: 5,
    propertyType: "Agricultural Plot",
    type: "buy",
    status: "active",
    featured: false,
    features: ["Dairy Operation", "Processing Unit", "Cattle Shed", "Cold Storage"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&h=600&fit=crop"]
  },
  {
    title: "Shopping Mall Space for Lease",
    description: "Prime retail space in popular shopping mall with high footfall and anchor tenants.",
    price: 150000,
    location: "City Mall, Ahmednagar",
    address: "Shop No. 45-46, City Mall, Central Avenue",
    beds: 0,
    baths: 1,
    area: 1200,
    areaUnit: "sqft",
    yearBuilt: 2020,
    parking: 0,
    propertyType: "Shop",
    type: "rent",
    status: "active",
    featured: true,
    features: ["Mall Location", "High Footfall", "Anchor Tenants", "Central AC"],
    maharera_registered: true,
    maharera_number: "P52100047915",
    images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop"]
  },
  {
    title: "Vintage Bungalow for Restoration",
    description: "Colonial-era bungalow with heritage value, perfect for restoration and boutique hotel conversion.",
    price: 8500000,
    location: "Heritage Area, Ahmednagar",
    address: "Bungalow No. 7, Heritage Lane, Cantonment Area",
    beds: 6,
    baths: 4,
    area: 4200,
    areaUnit: "sqft",
    yearBuilt: 1935,
    parking: 3,
    propertyType: "Bungalow",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Heritage Property", "Colonial Architecture", "Large Compound", "Restoration Potential"],
    maharera_registered: false,
    maharera_number: null,
    images: ["https://images.unsplash.com/photo-1605276373954-0c4a0dac5b12?w=800&h=600&fit=crop"]
  },
  {
    title: "Tech Park Office with Modern Infrastructure",
    description: "State-of-the-art office space in tech park with fiber connectivity and modern amenities.",
    price: 12500000,
    location: "Tech Park, Ahmednagar",
    address: "Building C, Tech Park Phase I, MIDC Area",
    beds: 0,
    baths: 3,
    area: 4000,
    areaUnit: "sqft",
    yearBuilt: 2022,
    parking: 12,
    propertyType: "Office",
    type: "buy",
    status: "active",
    featured: true,
    features: ["Tech Infrastructure", "Fiber Connectivity", "Modern Amenities", "Flexible Layout"],
    maharera_registered: true,
    maharera_number: "P52100047916",
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop"]
  },
  {
    title: "Apartment Complex for Bulk Sale",
    description: "Complete apartment complex with 24 units, perfect for investors or developers.",
    price: 75000000,
    location: "New Township, Ahmednagar",
    address: "Harmony Complex, New Township Development",
    beds: 48,
    baths: 48,
    area: 32000,
    areaUnit: "sqft",
    yearBuilt: 2021,
    parking: 30,
    propertyType: "Apartment Complex",
    type: "buy",
    status: "active",
    featured: true,
    features: ["24 Units", "Bulk Sale", "Ready to Occupy", "Investment Opportunity"],
    maharera_registered: true,
    maharera_number: "P52100047917",
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop"]
  }
];

async function addAhmednagarProperties() {
  try {
    console.log("Starting to add 50 Ahmednagar properties...");
    
    // Get available agents to assign properties
    const availableAgents = await db.select().from(agents).limit(5);
    console.log(`Found ${availableAgents.length} agents for property assignment`);
    
    if (availableAgents.length === 0) {
      console.error("No agents found. Please add agents first.");
      return;
    }
    
    let successCount = 0;
    
    for (let i = 0; i < ahmednagarProperties.length; i++) {
      const property = ahmednagarProperties[i];
      
      // Assign agent randomly from available agents
      const randomAgent = availableAgents[Math.floor(Math.random() * availableAgents.length)];
      
      try {
        const propertyData = {
          ...property,
          agentId: randomAgent.id,
          // Convert area to number if it's in acres
          area: property.areaUnit === "acres" ? property.area * 43560 : property.area,
          areaUnit: property.areaUnit === "acres" ? "sqft" : property.areaUnit,
          mapUrl: `https://maps.google.com/maps?q=${encodeURIComponent(property.location)}`,
          // Ensure parking is properly handled as integer or null
          parking: property.parking || null
        };
        
        await db.insert(properties).values(propertyData);
        successCount++;
        console.log(`✓ Added property ${i + 1}: ${property.title}`);
        
        // Add small delay to avoid overwhelming the database
        await new Promise(resolve => setTimeout(resolve, 100));
        
      } catch (error) {
        console.error(`✗ Failed to add property ${i + 1}: ${property.title}`);
        console.error("Error:", error.message);
      }
    }
    
    console.log(`\n🎉 Successfully added ${successCount} out of ${ahmednagarProperties.length} properties from Ahmednagar district!`);
    console.log("\nProperty types added:");
    console.log("- Villas and Independent Houses");
    console.log("- Apartments and Studio Apartments");
    console.log("- Commercial Shops and Offices");
    console.log("- Agricultural and Orchard Land");
    console.log("- Industrial and Manufacturing Units");
    console.log("- Luxury Properties (Farmhouses, Penthouses)");
    console.log("- Budget Properties and Plots");
    console.log("- Rental Properties");
    console.log("- Heritage and Unique Properties");
    console.log("- Specialized Properties (Hospitals, Schools, etc.)");
    
  } catch (error) {
    console.error("Error adding Ahmednagar properties:", error);
  }
}

// Run the script
addAhmednagarProperties().catch(console.error);